minimumReleaseAge: 1440
blockExoticSubdeps: true
strictDepBuilds: true

allowBuilds:
  '@parcel/watcher': true
  classic-level: true
  edgedriver: true
  esbuild: true
  geckodriver: true
  obsidian-integration-testing: true
  svelte-preprocess: true

overrides:
  fast-uri: 3.1.2
  fast-xml-builder: 1.2.0
  serialize-javascript: 7.0.5
