import { execFileSync } from 'node:child_process';
import { readFileSync, statSync, writeFileSync, existsSync } from 'node:fs';

/** Bake declaration/family provenance into the shipped provider; never consult Git at runtime. */
const sources = [
	'logicSasiBootstrap', 'logicSasiMoveActions', 'logicSasiHoverActions',
	'logicSasiSceneActions', 'logicSasiToolbarActions', 'logicToolbarMenuCatalog',
	'logicSasiSearchActions', 'logicSasiSettingsActions', 'logicSasiSettingScene',
	'logicGroupSelectionTransaction', 'logicApiScene', 'logicApiSceneModel',
].map((name) => `src/logic/${name}.ts`);
sources.push('src/main.ts');
type Lifecycle = { createdAt: number; updatedAt: number; source: string; precision: 'declaration-module' };
const catalogue: Record<string, Lifecycle> = {};
function git(...args: readonly string[]): string {
	return execFileSync('git', [...args], { encoding: 'utf8', env: { ...process.env, GIT_MASTER: '1' }, maxBuffer: 16 * 1024 * 1024 });
}
function keys(text: string): Set<string> {
	const result = new Set<string>();
	for (const match of text.matchAll(/['"`]([^'"`\n]{3,150})['"`]/g)) {
		const value = match[1];
		if (!value) continue;
		const key = value.includes('${') ? value.slice(0, value.indexOf('${')) : value;
		if (!/^[a-zA-Z][a-zA-Z0-9_.:/-]*$/.test(key)) continue;
		const before = text.slice(Math.max(0, (match.index ?? 0) - 30), match.index);
		if (/^(vaultman\.|chrome:|view_menu[.:]|sort_menu[.:]|scene_menu[.:]|node_|cell_|panel|settings-|barTransaction|searchbox|apply-queue$|open$|open-updates$|focus-)/.test(key) || /\bid\s*:\s*$/.test(before)) result.add(key);
	}
	return result;
}
const implementationDate = (source: string): number => {
	const committed = Number(git('log', '-1', '--format=%at', '--', source).trim()) * 1000;
	return git('status', '--porcelain', '--', source).trim()
		? Math.max(committed, Math.trunc(statSync(source).mtimeMs)) : committed;
};
const toolbarUpdated = Math.max(implementationDate('src/components/pages/pageFilters.svelte'), implementationDate('src/VaultmanFrame.svelte'));
const apiUpdated = implementationDate('src/modals/modalSasiInspector.ts');
for (const source of sources) {
	if (!existsSync(source)) continue;
	const history = git('log', '--reverse', '--format=%H|%at', '--', source).trim().split('\n').filter(Boolean);
	const created = new Map<string, number>();
	let updatedAt = 0;
	for (const line of history) {
		const [commit, epoch] = line.split('|');
		if (!commit || !epoch) continue;
		const timestamp = Number(epoch) * 1000;
		updatedAt = Math.max(updatedAt, timestamp);
		let text: string;
		try { text = git('show', `${commit}:${source}`); } catch { continue; }
		for (const key of keys(text)) if (!created.has(key)) created.set(key, timestamp);
	}
	const dirty = git('status', '--porcelain', '--', source).trim() !== '';
	if (dirty) updatedAt = Math.max(updatedAt, Math.trunc(statSync(source).mtimeMs));
	for (const key of keys(readFileSync(source, 'utf8'))) {
		const createdAt = created.get(key) ?? (dirty ? Math.trunc(statSync(source).mtimeMs) : undefined);
		if (createdAt === undefined || updatedAt === 0) continue;
		const prior = catalogue[key];
		const implementationUpdated = key.startsWith('vaultman.toolbar.') || key.startsWith('vaultman.scene.engine.') || key.startsWith('vaultman.scene.goto.')
			? toolbarUpdated : key === 'vaultman.scene.apiscene' ? apiUpdated : 0;
		catalogue[key] = {
			createdAt: Math.min(prior?.createdAt ?? createdAt, createdAt),
			updatedAt: Math.max(prior?.updatedAt ?? updatedAt, updatedAt, implementationUpdated),
			source: prior?.source ?? source, precision: 'declaration-module',
		};
	}
}
const output = 'src/logic/logicSasiLifecycleCatalogue.ts';
const data = JSON.stringify(Object.fromEntries(Object.entries(catalogue).sort(([a], [b]) => a.localeCompare(b))));
const content = `// Generated by scripts/generate-sasi-lifecycle.mts. Pure provenance data.\nimport type { SasiLifecycle } from './logicSasiLifecycle';\nexport const SASI_LIFECYCLE_CATALOGUE: Readonly<Record<string, SasiLifecycle>> = ${data};\n`;
if (!existsSync(output) || readFileSync(output, 'utf8') !== content) writeFileSync(output, content);
